app/user/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import SubmitField
from .. import pictures

class UploadForm(FlaskForm):
    avatar = FileField(u'头像上传', validators=[
        FileAllowed(pictures, u'只能上传图片！'),
        FileRequired(u'未选择文件！')])
    submit = SubmitField(u'上传')

app/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from . import views, errors

app/user/views.py
# -*- coding: utf-8 -*-

from werkzeug import secure_filename
from flask import render_template, redirect, url_for, request, flash, current_app
from flask_login import current_user, login_required
from . import user
from ..main import main
from .. import db, pictures
from .forms import UploadForm
from ..models import User, Post, Tag

@user.route('/user-profile/', methods=['GET', 'POST'])
@login_required
def profile():
    form = UploadForm()
    if request.method == 'POST' and 'avatar' in request.files:
        filename = pictures.save(request.files['avatar'])
        file_url = current_app.config['RENDER_PICTURES_DEST'] + filename
        current_user.avatar = file_url
        db.session.add(current_user)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('user/profile.html', form=form)

app/templates/user/profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<form action="{{ url_for('user.profile') }}" method="POST" enctype="multipart/form-data">
	{{ form.hidden_tag() }}
	{{ wtf.form_field(form.avatar) }}
	{{ wtf.form_field(form.submit) }}
</form>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}